a = input("digite algo: ")
print("o tipo primitivo desse valor é ", type(a))
print("so tem espaço?",a.isspace())
print("é um numero?",a.isnumeric())
print("é alfabetico?",a.isalpha())
print("é alfanumerico?",a.isalnum())
print("está em maiusculas?",a.isupper())
print("está em minusculas?",a.islower())
print("está capitalizada?",a.istitle())
